/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;
import java.awt.Button;
import java.awt.Label;
import java.awt.TextArea;
import java.awt.TextField;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author jl-h
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        textArea2 = new java.awt.TextArea();
        Bbruta = new java.awt.Button();
        textoSalida = new java.awt.TextArea();
        Ctexto = new java.awt.TextField();
        Bbnombre = new java.awt.Button();
        Biarchivo = new java.awt.Button();
        bLeer = new java.awt.Button();
        label2 = new java.awt.Label();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bbruta.setLabel("Busqueda por ruta");
        Bbruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbrutaActionPerformed(evt);
            }
        });

        Bbnombre.setLabel("Busqueda por nombre");
        Bbnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbnombreActionPerformed(evt);
            }
        });

        Biarchivo.setActionCommand("Insertar");
        Biarchivo.setLabel("Insertar archivo");
        Biarchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BiarchivoActionPerformed(evt);
            }
        });

        bLeer.setLabel("Leer archivo");
        bLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLeerActionPerformed(evt);
            }
        });

        label2.setText("Nombre o ruta a buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Bbnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bbruta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Biarchivo, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(bLeer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(79, 79, 79))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ctexto, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(textoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(Ctexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bbnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Biarchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bbruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLeer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BbnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbnombreActionPerformed
        if(Ctexto.getText()==null)
            JOptionPane.showMessageDialog(null, "Digíte el nombre del archivo a buscar en el cuadro de texto");
        else{
            String s=Arbol.buscar(Ctexto.getText());
            textoSalida.setText(s+"\n"); 
            Ctexto.setText("");
            
        }
    }//GEN-LAST:event_BbnombreActionPerformed

    public Button getbLeer() {
        return bLeer;
    }

    private void bLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLeerActionPerformed
        JOptionPane.showMessageDialog(null, "Se está cargando el archivo de texto en la estructura de datos \nEsto podrìa tardar unos segundos.");
        leerTxt.leer();
        JOptionPane.showMessageDialog(null, "Se ha cargado correctamente el archivo.");
    }//GEN-LAST:event_bLeerActionPerformed

    private void BbrutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbrutaActionPerformed
        if(Ctexto.getText()==null)
            JOptionPane.showMessageDialog(null, "Digíte la ruta del archivo a buscar en el cuadro de texto");
        else{
            String s=Arbol.buscarPorRuta(Ctexto.getText());
            textoSalida.setText(s+"\n");
            Ctexto.setText("");            
        }
    }//GEN-LAST:event_BbrutaActionPerformed

    private void BiarchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BiarchivoActionPerformed
    AddFrame a=new AddFrame();
    a.setVisible(true);
    }//GEN-LAST:event_BiarchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        leerTxt.leer();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new Pantalla().setVisible(true);
            }
        });
    }

    public Button getBbnombre() {
        return Bbnombre;
    }

    public Button getBbruta() {
        return Bbruta;
    }

    public TextField getCtexto() {
        return Ctexto;
    }

    public Button getButton6() {
        return Biarchivo;
    }

    public Label getLabel1() {
        return label1;
    }

    public TextArea getTextArea2() {
        return textArea2;
    }

    public TextArea getTextoSalida() {
        return textoSalida;
    }
    
    public static String listar(Directorio d) {
        if (d.getListaArchivos().isEmpty()) {
            return "No Existen Archivos dentro de este directorio";
        } else {
            String s="";
            s+="Archivos existentes en: " + d.nombre+"\n";
            for (int i = 0; i < d.getListaArchivos().size(); i++) {
                s+="\n[" + i + "] " + d.getListaArchivos().get(i);
            }
            return s;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Bbnombre;
    private java.awt.Button Bbruta;
    private java.awt.Button Biarchivo;
    private java.awt.TextField Ctexto;
    private java.awt.Button bLeer;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.TextArea textArea2;
    private java.awt.TextArea textoSalida;
    // End of variables declaration//GEN-END:variables
}
